name:                paypal-notification-resend
version:             0.1.0.0
github:              "Vincibean/PayPal-Notification-Resend"
license:             GPL-3.0
author:              "Vincibean"
maintainer:          "andrebessi00@gmail.com"
copyright:           "2020 Vincibean"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/paypal-notification-resend#readme>

dependencies:
- base >= 4.7 && < 5
- wreq
- bytestring
- containers
- lens
- aeson
- lens-aeson
- text

library:
  source-dirs: src

executables:
  paypal-notification-resend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - paypal-notification-resend

tests:
  paypal-notification-resend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - paypal-notification-resend
